### PR TITLE
More int()ification

### PR DESCRIPTION
**Pull request by dmcc**
`status()`: now returns an integer volume level.
`info()`: `int()`ify section numbers if possible. Try parsing values as floats, falling back to ints, falling back to strings.
`set_volume()`, `volup()`, `voldown()`: forces argument to be an integer.
`volume()`: improve docstring.

This is in preparation for a corresponding fix to Home Assistant's [`vlc_telnet/media_player.py`](https://github.com/home-assistant/core/blob/dev/homeassistant/components/vlc_telnet/media_player.py), which I'll make after these changes are on PyPI.

### CODE REVIEW

**Comment by dmcc** [comment]
(friendly ping :))

**Comment by rodripf** [comment]
Sorry for the delay! When I'm home I'll push the changes to pypi

**Comment by dmcc** [comment]
Thanks Rodrigo!

**Comment by rodripf** [comment]
It's on PyPI now! https://pypi.org/project/python-telnet-vlc/
Sadly I'm short on time those months, I didn't manage to make some spare time to work in HA :(
I hope to retake an active role soon.

**Pull request merged**
